version: '2'
services:
  taskd:
    image: jenserat/taskd
    ports:
      - "53589:53589"
    volumes:
      - taskd-data:/var/taskd
  nagger:
    build: .
    tty: true
    stdin_open: true
    volumes:
      - .:/taskwarrior-nagger
      - taskwarrior-taskrc:/root/.taskrc
      - taskwarrior-task:/root/.task
    depends_on:
      - taskd
volumes:
  taskd-data:
    driver: local
  taskwarrior-taskrc:
    driver: local
  taskwarrior-task:
    driver: local
