version: '2'
services:
  web:
    build: .
    command: /usr/local/bin/server.sh
    ports:
      - "53589:53589"
    tty: true
    stdin_open: true
    volumes:
      - taskddata:/var/taskd
volumes:
  taskddata:
    driver: local
